# Generated by Django 5.2.7 on 2025-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admission_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
                ('class_name', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('mathematics', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('english', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.FloatField()),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
