# Generated by Django 5.2.7 on 2025-11-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mathematics',
            new_name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='F', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='result',
            field=models.CharField(default='Fail', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
